### ISSUE TITLE
http 403 when attempting to access github

### ISSUE THREAD

**Issue by TonyPeach** [chrispugh88/SeleniumPegaTest#1]
I am using a VMWare Horizon Client.

When I type
git clone https://TonyPeach@github.com/xxx/seleniumpegatest.git
I get the following messages finishing with the error 403

Cloning into 'seleniumpegatest'...
fatal: unable to access 'https://TonyPeach@github.com/xxx/seleniumpegate
st.git/': The requested URL returned error: 403

People in my team are not getting this error, so I suspect something in the VM, but the administrator responsible for VM's doesn't think so

How can I find out what is causing this error please?
I cannot find any logs on my pc. Do I need to turn logging on and, if so, how?

I'd be happy to provide any further information on request

**Comment by chrispugh88** [comment]
Turned out some of the proxy information in the .gitconfig file was case sensitive which wasn't previously realised. Issue is closed now.
